### ISSUE TITLE
First example: work in progress

### ISSUE THREAD

**Issue by aroberge** [friendly-traceback/friendly-pandas#1]
# Important
friendly-pandas now needs to be run with friendly_traceback version 0.5.57.

## Starting example

The content of the file `example.py` is as follows:
```
import pandas as pd

df = pd.DataFrame([[10, 20, 30], [40, 50, 60]],
                  index=list("ab"),
                  columns=list("xyz"))
``` 

Here's a sample session PRIOR TO A FEW CHANGES NOTED BELOW:
```
> python -m friendly

friendly-traceback: 0.5.54
friendly: 0.5.39
Python: 3.10.6
Type 'Friendly' for help on special functions/methods.


[1]: from friendly_pandas import register

[2]: from example import df

[3]: df.loc["y"]

Traceback (most recent call last):
  File "LOCAL:\pandas\core\indexes\base.py", line 3629, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'y'

    The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  Code block [3], line 1
    df.loc["y"]
KeyError: 'y'

To retrieve a column, just use square brackets: df["y "]

[4]: df.loc["w"]

Traceback (most recent call last):
  File "LOCAL:\pandas\core\indexes\base.py", line 3629, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'w'

    The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  Code block [4], line 1
    df.loc["w"]
KeyError: 'w'


[5]: why()

You tried to retrieve an unknown row. The valid values are: a, b.

[6]: where()

Exception raised on line 1 of code block [4].

     > 1| df.loc["w"]

    df:      x   y   z
a  10  20  30
b  40  50  60
```
Note: since I used Friendly, the highlighting of the problematic code is done using a red background, which is not reproduced in the example above.

Instead of trying only something like `df.loc[...]`, one can try to do an assignment; something like
```
column = df.loc["y"]
```
It will still work.

## Chained exception

Note that the traceback not only includes code from the user but also a notice that another exception was raised, this one entirely inside Pandas' code. This information is not useful to someone just learning Python (or anyone else really, except perhaps pandas developers?) and it would make sense to not include it.  This was done in a later version as noted below.

**Comment by aroberge** [comment]
Note: the existing code (version 0.0.2) prevents the normal handling of `KeyError` as it completely replaces the existing handling from friendly_traceback. This needs to be modified.

This has been fixed in version 0.0.3
```
[1]: from friendly_pandas import register

[2]: from example import df

[3]: df.loc['y']

Traceback (most recent call last):
  File "LOCAL:\pandas\core\indexes\base.py", line 3629, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'y'

    The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  Code block [3], line 1
    df.loc['y']
KeyError: 'y'


[4]: d = {'aa': 1, 'bc': 2}

[5]: d['ab']

Traceback (most recent call last):
  Code block [5], line 1
    d['ab']
KeyError: 'ab'

Did you mean 'aa'?
```

**Comment by aroberge** [comment]
Untested addition: if the name of a row has 2 or more characters and is misspelled, some information about possible correct values should be provided.

**Comment by aroberge** [comment]
Broken example: using `parser.add()` effectively appends and default values from friendly_traceback prevent friendly_pandas from registering. I need to define `parser.insert` instead.

**Comment by aroberge** [comment]
I have added four unit tests to demonstrate three cases handled by friendly_pandas and a fourth one by friendly_traceback. These are meant to be run using pytest.

**Comment by aroberge** [comment]
With friendly_pandas version 0.0.6 and friendly-traceback 0.5.56, traceback from chained exceptions are suppressed by default:
![image](https://user-images.githubusercontent.com/629698/189560750-34bdbda7-a91d-49fd-a515-2056454380f5.png)

Variables shown at the end of `where()` that require more than one line are not indented, which does not look good. This would need to be fixed in `friendly_traceback` itself, which might not be easy to do, but would be worth it.

The most recent friendly-pandas version (0.0.7 using friendly-traceback 0.5.57) would yield the same output: the only relevant change is some new name for a method in friendly-traceback.

**Comment by aroberge** [comment]
Latest version:
![image](https://user-images.githubusercontent.com/629698/190918930-c5bfc3a4-b2c4-40ba-ac5e-3b6a1d1d709a.png)
